### ISSUE TITLE
Where can I see the changes after running the code? Isn't there a text file to save the results to?

### ISSUE THREAD

**Issue by me-suzy** [rajat4665/web-scraping-with-python#4]
hello, sir.  So, I am using PyScripter. Also, I install the library jupyter with CMD

`py -m pip install jupyter` - succesfuly
`py -m pip install selenium` - succesfuly

I run the code. succesfuly. Great Scraping.

But The problem. Where can I see the changes after running the code? Isn't there a text file to save the results to? Because this is much more important. 

So, How can I save the results from scraping in a new File ?

**Comment by rajat4665** [comment]
well I am working on it, thanks for the acknowledgment, I have added a new python file  web_scraping_command_line_tool.py  from here you can scrap data, and results will be stored in the scraped_data.json file.
Currently, it's a beta version, I am planning to add more features in that.
